# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe945f5ad9a9c848e55b93e96bb26e573dce47fb4b4ed2062a78112d3fac4acff26a0e209e529589ba225101cb260fe5a6e2dbd969731d4a6e8c46cbeae80060

test:
  secret_key_base: 74b658e4ac48f80b6c4f731f5cf7f603ffda2cd167d48c1720939668bcfff11a8d864e7f22ada0292156bc86da9252d566f6468f5e9116cc55fc7554222b037c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
